# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    binary: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
    files:
      - README*
dockers:
  # You can have multiple Docker images.
  -
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    goarch: amd64
    image_templates:
      - gcr.io/plasma-column-128721/go-quic-proxy:{{ .Tag }}
  -
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    goarch: amd64
    image_templates:
      - gcr.io/plasma-column-128721/go-quic-proxy:latest
    skip_push: auto

nfpms:
  - formats:
      - deb
    bindir: /usr/bin

# artifactories:
#   - name: 6rs
#     target: https://sixriver.jfrog.io/sixriver/binaries/{{ .ProjectName }}/{{ .Version }}/
#     username: 6rs-machine

