# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - main: ./main.go
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
    files:
      - README*
nfpms:
  - formats:
      - deb
    bindir: /usr/bin

# artifactories:
#   - name: 6rs
#     target: https://sixriver.jfrog.io/sixriver/binaries/{{ .ProjectName }}/{{ .Version }}/
#     username: 6rs-machine

